---
  application_users:
    - user_id: test_user00
      password: test_password00
      email: test_user00@testemail.com
      active: True
    - user_id: test_user01
      password: test_password01
      email: test_user01@testemail.com
      active: True

  application_map_dictionary: # Keys will be replaced with values
    Lorem: 'Lorem©'
    Ipsum: 'Ipsum©'
    Latin: 'Latin©'
    Renaissance: 'Renaissance©'
